[project]
name = "pianomodel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.8",
    "mir-eval>=0.8.2",
    "numpy",
    "onnx>=1.22.0",
    "onnxruntime>=1.18,<1.21",
    "pretty-midi>=0.2.10",
    "ruff",
    "sounddevice>=0.5.5",
    "soundfile>=0.13.1",
    "torch",
    "torchaudio>=2.8.0",
    "tqdm>=4.67.3",
]
